import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Hero from '@/homepage/hero';
import FeaturedPosts from '@/homepage/featured-posts';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <FeaturedPosts />
      </main>
    </>
  );
};

export default Home;
